In [ ]:
import pandas as pd

To preprocess the natural disaster data, we imported the EM-DAT data as a pandas DataFrame. Then, we used the groupby operation and the count aggregate function to calculate the number of natural disasters experienced by each country by year.

To preprocess the food supply data, we imported the FAOSTAT data as a pandas DataFrame. Because the database used different methodologies before and after 2010, the data was divided into two parts that have the same structure. We first merged the two datasets vertically, then removed all columns except for “Area”, “Year”, and “Value”. Lastly, we renamed the “Value” column as “Food Supply (kcal/capita/day)”.

# Natural Disasters

In [ ]:
nd_df = pd.read_excel('Natural_Disasters_Copy.xlsx')
nd_df

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damages ('000 US$),"Insured Damages, Adjusted ('000 US$)",Total Damages ('000 US$),"Total Damages, Adjusted ('000 US$)",CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
0,1985-0063-BGD,1985,63,NaN,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,...,NaN,NaN,NaN,50000.0,125954.0,39.696934,NaN,NaN,NaN,NaN
1,1985-0132-COL,1985,132,NaN,Natural,Geophysical,Volcanic activity,Ash fall,NaN,Nevado Del Ruiz,...,NaN,NaN,NaN,1000000.0,2519086.0,39.696934,NaN,NaN,NaN,NaN
2,1985-9400-AGO,1985,9400,NaN,Natural,Climatological,Drought,Drought,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,39.696934,NaN,NaN,NaN,NaN
3,1985-0241-ALB,1985,241,NaN,Natural,Hydrological,Landslide,Avalanche,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,39.696934,NaN,NaN,NaN,NaN
4,1985-0244-ALB,1985,244,NaN,Natural,Meteorological,Extreme temperature,Severe winter conditions,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,39.696934,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12163,2022-0255-COD,2022,255,EP-2022-000202,Natural,Biological,Epidemic,Viral disease,NaN,Plague,...,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,14992,Ituri (Adm2).
12164,2022-0263-COD,2022,263,EP-2022-000205,Natural,Biological,Epidemic,Viral disease,NaN,Ebola Virus Disease,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12165,2022-0569-ZWE,2022,569,EP-2022-000304,Natural,Biological,Epidemic,Viral disease,NaN,Measles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12166,2022-0201-TLS,2022,201,EP-2022-000162,Natural,Biological,Epidemic,Viral disease,NaN,Dengue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12167,2022-0650-SSD,2022,650,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,2747;2751;2754;2765;2768;37021,NaN,"Jonglei, Northern Bahr El Ghazal, Unity, Upper..."

In [ ]:
nd_final_df = nd_df.groupby(['Country', 'Year'])[['Dis No']].count().reset_index()
nd_final_df.rename(columns={'Dis No':'Number of Disasters'}, inplace=True)
nd_final_df

          Country  Year  Number of Disasters
0     Afghanistan  1987                    1
1     Afghanistan  1988                    1
2     Afghanistan  1990                    1
3     Afghanistan  1991                    6
4     Afghanistan  1992                    3
...           ...   ...                  ...
4084     Zimbabwe  2017                    2
4085     Zimbabwe  2018                    1
4086     Zimbabwe  2019                    2
4087     Zimbabwe  2021                    2
4088     Zimbabwe  2022                    3

[4089 rows x 3 columns]

In [ ]:
nd_final_df.to_csv('Natural_Disasters_Cleaned')

# Food Balance

In [ ]:
fb_df = pd.read_csv('Food_Supply.csv', encoding='latin-1')
fb_df

,ï»¿Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,FBSH,"Food Balances (-2013, old methodology and popu...",4,Afghanistan,664,Food supply (kcal/capita/day),S2901,Grand Total,1961,1961,kcal/capita/day,2999,E,Estimated value
1,FBSH,"Food Balances (-2013, old methodology and popu...",4,Afghanistan,664,Food supply (kcal/capita/day),S2901,Grand Total,1962,1962,kcal/capita/day,2917,E,Estimated value
2,FBSH,"Food Balances (-2013, old methodology and popu...",4,Afghanistan,664,Food supply (kcal/capita/day),S2901,Grand Total,1963,1963,kcal/capita/day,2698,E,Estimated value
3,FBSH,"Food Balances (-2013, old methodology and popu...",4,Afghanistan,664,Food supply (kcal/capita/day),S2901,Grand Total,1964,1964,kcal/capita/day,2953,E,Estimated value
4,FBSH,"Food Balances (-2013, old methodology and popu...",4,Afghanistan,664,Food supply (kcal/capita/day),S2901,Grand Total,1965,1965,kcal/capita/day,2956,E,Estimated value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8987,FBS,Food Balances (2010-),716,Zimbabwe,664,Food supply (kcal/capita/day),S2901,Grand Total,2015,2015,kcal/capita/day,1919,E,Estimated value
8988,FBS,Food Balances (2010-),716,Zimbabwe,664,Food supply (kcal/capita/day),S2901,Grand Total,2016,2016,kcal/capita/day,1957,E,Estimated value
8989,FBS,Food Balances (2010-),716,Zimbabwe,664,Food supply (kcal/capita/day),S2901,Grand Total,2017,2017,kcal/capita/day,1862,E,Estimated value
8990,FBS,Food Balances (2010-),716,Zimbabwe,664,Food supply (kcal/capita/day),S2901,Grand Total,2018,2018,kcal/capita/day,1875,E,Estimated value
8991,FBS,Food Balances (2010-),716,Zimbabwe,664,Food supply (kcal/capita/day),S2901,Grand Total,2019,2019,kcal/capita/day,1707,E,Estimated value

In [ ]:
fb_final_df = fb_df[['Area', 'Year', 'Value']]
fb_final_df.rename(columns={'Value':'Food Supply (kcal/capita/day)'}, inplace=True)
fb_final_df

C:\Users\lovea\AppData\Local\Temp\ipykernel_93064\2614086861.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fb_final_df.rename(columns={'Value':'Food Supply (kcal/capita/day)'}, inplace=True)

             Area  Year  Food Supply (kcal/capita/day)
0     Afghanistan  1961                           2999
1     Afghanistan  1962                           2917
2     Afghanistan  1963                           2698
3     Afghanistan  1964                           2953
4     Afghanistan  1965                           2956
...           ...   ...                            ...
8987     Zimbabwe  2015                           1919
8988     Zimbabwe  2016                           1957
8989     Zimbabwe  2017                           1862
8990     Zimbabwe  2018                           1875
8991     Zimbabwe  2019                           1707

[8992 rows x 3 columns]

In [ ]:
fb_final_df.to_csv('Food_Supply_Cleaned')